### ISSUE TITLE
Enable coaches to change their profile information

### ISSUE THREAD

**Issue by horacioh** [reactgraphqlacademy/reactgraphqlacademy#282]
I wanted to edit my profile information (current job, picture, email, twitter, links...) but seems that all the data now is outside the repo?

is there a way to update this by ourselves?

thanks!

**Comment by alexlbr** [comment]
Hi  @horacioh , the content is being moved to Sanity.io. We are operating right now with the free tier so we only 3 users at the moment. Please send the changes you want to Lena and she'll update it. Ideally, each coach will have an account to create/ update content. Sorry for the current inconvenient.

**Comment by horacioh** [comment]
not an inconvenient at all!!

maybe this specific part can be in code so the flexibility is better? that would mean less work and time from your side :)

is this something you are ok with? I can help with the code setup :)

**Comment by alexlbr** [comment]
Thanks for volunteering :) If it's 
> not an inconvenient at all!!
would you mind to send the changes to Lena for the time being? :)
That's probably the easiest option right now since the profiles are already migrated to Sanity, and maybe the next time you want to make we have sorted out the access for everyone to Sanity.io

**Comment by horacioh** [comment]
that sounds perfect! :)

thanks

**Comment by horacioh** [comment]
closing this since the way to change profile data right now is sending the changes to Lena 👍
